version: '3.8'

services:
  nas:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nas_user
      POSTGRES_PASSWORD: nas_pass
      POSTGRES_DB: nas_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

